### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by KevinNitroG** [KevinNitroG/FFmpeg-Copy-GA#3]
- [ ] Create 20 concurrent jobs, distribute links like MSRB GA
- [ ] Custom ffmpeg command using variable
- [ ] Delete old workflows and releases
